Repository RedDragonSquad/Hotpot-Buddy, pull requests merged in 2022-09, with the labels that each got.

#22 [HOT-56] Abstract timer logic from FoodTimerList component
  client/src/pages/pot-instance/PotInstance.tsx
  client/src/pages/pot-instance/components/FoodTimer/FoodTimer.tsx
  client/src/pages/pot-instance/components/FoodTimerList/FoodTimer.tsx
  client/src/pages/pot-instance/components/FoodTimerList/FoodTimerList.tsx
  client/src/pages/pot-instance/components/FoodTimerList/styles.module.css
  client/src/pages/pot-instance/components/PotView/PotView.tsx
  client/src/pages/pot-instance/components/index.tsx
  client/src/pages/pot-instance/models.tsx
Labels: v2

#23 [HOT-58] Timer re-rendering un-necessary buttons in pot instance
  client/src/pages/pot-instance/PotInstance.tsx
  client/src/pages/pot-instance/components/PotView/PotView.tsx
Labels: bug, v2

#24 [HOT-59] AddIngredients component re-rendering on debounce function
  client/src/pages/pot-instance/components/AddIngredients/AddIngredients.tsx
  client/src/pages/pot-instance/components/IngredientsList/IngredientsList.tsx
Labels: bug, v2

#25 [HOTFIX] Address issues with memorized AddIngredients component.
  client/src/pages/pot-instance/components/PotView/PotView.tsx
Labels: bug

#26 [HOT-50] Expand Ingredient List
  client/public/mockData/ingredients.json
Labels: v2

#28 [HOT-37] Create simple view bar component
  client/src/components/StackedProgressBar.tsx
  client/src/components/styles.module.css
  client/src/pages/pot-instance/components/IngredientsList/IngredientsList.tsx
  client/src/pages/pot-instance/components/PotView/PotView.tsx
  client/src/pages/pot-instance/components/SimpleTimerView/SimpleTimerView.tsx
  client/src/pages/pot-instance/models.tsx
  client/src/utils/colors.tsx
Labels: v2

#29 [HOT-39] Add colour related attributes for categories
  client/src/pages/pot-instance/components/SimpleTimerView/SimpleTimerView.tsx
  client/src/utils/colors.tsx
Labels: v2

#27 [HOT-53] Pixelart + MUI Themes
  client/public/assets/ox bone.svg
  client/public/assets/spicy.svg
  client/public/assets/tomato.svg
  client/src/App.tsx
  client/src/pages/pot-instance/PotInstance.tsx
  client/src/pages/pot-instance/components/LandingPage/LandingPage.tsx
  client/src/pages/pot-instance/components/LandingPage/styles.module.css
  client/src/pages/pot-instance/styles.module.css
  client/src/utils/muiThemes.tsx
  client/src/utils/potFlavors.tsx
Labels: v2
